### PR TITLE
Centralizes project name's styled H2 in Project.js and adds secDevLabs inverted logo.

### PR DESCRIPTION
**Pull request by LFRusso**

### CODE REVIEW

**Comment by markiing** [comment]
hey @LFRusso , you can remove the inverted logo as i said [here](https://github.com/globocom/opensource/issues/71).

**Comment by markiing** [comment]
@LFRusso we have a problem about the color, the `h2` is black and don't have a good constrast in home page.
Logo

We have to look the vertical align too, if you just do  `justify-content: center` it doesn't solve the vertical align problem
Logo 3


Could you fix these points too? 🚀

**Comment by LFRusso** [comment]
Thanks for the feedback, I was just now taking a look at it! Also, another thing I've noticed when taking a closer look at the component [here](https://github.com/globocom/opensource/blob/3564c6a26349e21ef0005383e7b958bbc25fec32/src/components/Project/Project.js#L239) (and then confirmed when checking it in the mobile version) is that because of the way it is structured, the *NavButton* for the project description is not rendered when there is no image attached to the project, basically making the description inaccessible in mobile.

mobilenav

I'll try changing some more things to fix this and hopefully get back soon.

**Comment by marcelometal** [comment]
@LFRusso  ping?!

**Comment by marcelometal** [comment]
I’m closing this issue because it has been inactive for a few weeks.

**Pull request closed without merging**
